const Constants = {
  PAGE_IS_READY: 'PAGE_IS_READY',
  PAGE_TRANSITION_IN: 'PAGE_TRANSITION_IN',
  PAGE_TRANSITION_OUT: 'PAGE_TRANSITION_OUT',
  PAGE_TRANSITION_OUT_COMPLETE: 'PAGE_TRANSITION_OUT_COMPLETE',
  PAGE_TRANSITION_IN_COMPLETE: 'PAGE_TRANSITION_IN_COMPLETE',
  PAGE_TRANSITION_IN_PROGRESS: 'PAGE_TRANSITION_IN_PROGRESS',
  PAGE_TRANSITION_OUT_PROGRESS: 'PAGE_TRANSITION_OUT_PROGRESS',
  PAGE_TRANSITION_DID_FINISH: 'PAGE_TRANSITION_DID_FINISH'
}

export default Constants
